### ISSUE TITLE
Not finding interest group in target file 

### ISSUE THREAD

**Issue by Nellie001** [Nellie001/Masters_Pyralis#1]
https://github.com/Nellie001/Masters_Pyralis/blob/14ffa935c12bbc1c0cbef2c7bd6fd0aeb2264227/SARTools_pyralis.Rmd#L79

Hello! 

I have tried using both "Pyralis.target" and "Pyralis_protein_tabular" as the target file, but in both cases, R is unable to find my interest group in the target file. Although it doesn't seem to have issues finding the target file, so I don't think it's a path issue. Is there any chance you know what's happening?

Just whenever you have the time, I would appreciate some feedback. 

Thank you, 
Nellie

**Comment by Nellie001** [comment]
I am now using Pyralis.target.3 as my target file, but I'm having the same problem

**Comment by KField-Bucknell** [comment]
Hi Nellie-
First, I think that SARTools likes tsv files not csv files. 

Another possible issue is that you have a space in the "Back legs" value for "Group". I would definitely remove that.

Talk to you soon.
Prof. Field
